#!/usr/bin/env node
'use strict';

/** Native Codex adapter. Authored definitions remain in their original folders. */
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const K = require('./kload.js');

const HOME = os.homedir();
const CODEX = process.env.KLOAD_CODEX_DIR || process.env.CODEX_HOME || path.join(HOME, '.codex');
const USER_SKILLS = process.env.KLOAD_SKILLS_DIR || path.join(HOME, '.agents', 'skills');
const OWNER = 'Generated by kload for Codex';
const MAX_CONTEXT = 192 * 1024;
const hash = (s) => crypto.createHash('sha256').update(s).digest('hex');
const exists = (p) => { try { fs.lstatSync(p); return true; } catch { return false; } };
const real = (p) => { try { return fs.realpathSync(p); } catch { return path.resolve(p); } };
const json = (p, fallback = {}) => exists(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : fallback;
const safeName = (s) => typeof s === 'string' && /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(s);

function atomicWrite(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (exists(file) && fs.readFileSync(file, 'utf8') === content) return false;
  const temp = `${file}.${process.pid}.${crypto.randomBytes(4).toString('hex')}.tmp`;
  try { fs.writeFileSync(temp, content, { mode: 0o600 }); fs.renameSync(temp, file); }
  finally { if (exists(temp)) fs.unlinkSync(temp); }
  return true;
}

function scopePaths(root) {
  const user = root === null;
  const codex = user ? CODEX : path.join(root, '.codex');
  return { root, cwd: user ? HOME : root, codex,
    generated: path.join(codex, 'kload', 'generated'),
    agents: path.join(codex, 'agents'),
    skills: user ? USER_SKILLS : path.join(root, '.agents', 'skills') };
}

function scopes(cwd) {
  const roots = [];
  let dir = path.resolve(cwd);
  for (let i = 0; i < 12 && dir !== HOME; i++) {
    if (exists(path.join(dir, '.claude')) || exists(path.join(dir, '.codex', 'kload.json')) || exists(path.join(dir, '.codex', 'agents')) || exists(path.join(dir, '.agents', 'skills'))) roots.push(dir);
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return [scopePaths(null), ...roots.reverse().map(scopePaths)];
}

function config(cwd) {
  // Reuse kload's configured-root precedence, ancestor discovery, symlink
  // handling and explicit-path semantics. Codex-specific settings layer last.
  const cfg = K.loadConfig(cwd);
  for (const f of [path.join(CODEX, 'kload.json'), path.join(cwd, '.codex', 'kload.json')]) {
    const overrides = json(f);
    Object.assign(cfg, overrides);
  }
  for (const [key, leaf] of [['agentDirs', 'agents'], ['skillDirs', 'skills'], ['knowledgeDirs', 'knowledge']]) {
    if (!Array.isArray(cfg[key]) || cfg[key].some((p) => typeof p !== 'string')) throw new Error(`${key} must be an array of paths`);
    cfg[key] = K.effectiveDirs(cfg[key].map((p) => p.replaceAll('{codex}', CODEX)), cwd, cfg, leaf);
  }
  cfg.maxContextBytes = cfg.maxContextBytes || MAX_CONTEXT;
  if (!Number.isSafeInteger(cfg.maxContextBytes) || cfg.maxContextBytes < 1024 || cfg.maxContextBytes > 1024 * 1024) {
    throw new Error('maxContextBytes must be between 1024 and 1048576');
  }
  cfg.maxFileBytes = cfg.maxContextBytes;
  cfg.strictUtf8 = true;
  return cfg;
}

/** Only the documented scalar Codex overrides, not arbitrary YAML execution. */
function runtimeSettings(frontmatter, fm, cfg, name) {
  let overrides = {};
  const runtime = fm.runtimes;
  if (typeof runtime === 'string' && runtime.trim().startsWith('{')) {
    overrides = JSON.parse(runtime).codex || {};
  } else {
    const lines = frontmatter.split('\n');
    const start = lines.findIndex((l) => /^runtimes:\s*(?:#.*)?$/.test(l));
    if (start >= 0) {
      let child = -1, indentation = 0, body = [];
      for (let i = start + 1; i < lines.length; i++) {
        const l = lines[i];
        if (l.trim() && !/^\s/.test(l)) break;
        const m = /^(\s+)codex:\s*(?:#.*)?$/.exec(l);
        if (m) { child = i; indentation = m[1].length; continue; }
        if (child >= 0) {
          if (l.trim() && l.match(/^\s*/)[0].length <= indentation) break;
          body.push(l.slice(indentation + 2));
        }
      }
      overrides = K.parseYamlSubset(body.join('\n'));
    }
  }
  const settings = Object.assign({}, cfg.agentDefaults || {}, (cfg.agentOverrides || {})[name] || {}, overrides);
  const allowed = new Set(['model', 'model_reasoning_effort']);
  for (const [k, v] of Object.entries(settings)) {
    if (!allowed.has(k)) throw new Error(`Unsupported Codex runtime setting: ${k}`);
    if (typeof v !== 'string' || !v.trim()) throw new Error(`Invalid Codex ${k}`);
    settings[k] = v.replace(/\s+#.*$/, '').trim();
  }
  if (settings.model === 'inherit') delete settings.model;
  if (settings.model_reasoning_effort === 'inherit') delete settings.model_reasoning_effort;
  if (settings.model && /^(claude[-:]|opus(?:-|$)|sonnet(?:-|$)|haiku(?:-|$))/i.test(settings.model)) {
    throw new Error('A Claude model cannot be used as the Codex model override');
  }
  if (settings.model_reasoning_effort && !['none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max', 'ultra'].includes(settings.model_reasoning_effort)) {
    throw new Error('Invalid Codex model_reasoning_effort');
  }
  return settings;
}

function snapshot(kind, name, source, cwd) {
  const cfg = config(cwd);
  const raw = fs.readFileSync(source, 'utf8');
  const [frontmatter, body] = K.splitFrontmatter(raw);
  if (!frontmatter) throw new Error(`${name}: missing frontmatter`);
  const fm = K.parseYamlSubset(frontmatter);
  if (!safeName(name) || fm.name !== name) throw new Error(`${name}: name must match the source filename/directory`);
  if (!fm.description || typeof fm.description !== 'string') throw new Error(`${name}: missing description`);
  // A malformed config with knowledge must never look like an empty declaration.
  if (fm.config && typeof fm.config === 'string') JSON.parse(fm.config);
  const files = [...new Set(K.declaredKnowledge(fm).files)];
  const records = files.map((file) => {
    const rec = K.resolveKnowledgeFile(file, cwd, cfg);
    return { ...rec, sha256: rec.status === 'ok' ? hash(rec.content) : null };
  });
  const failures = records.filter((r) => r.status !== 'ok');
  if (failures.length) throw new Error(`${name}: ${failures.map((r) => `${r.declared}: ${r.detail}`).join('; ')}`);
  const settings = kind === 'agent' ? runtimeSettings(frontmatter, fm, cfg, name) : {};
  const untranslated = ['tools', 'disallowedTools', 'max_turns', 'maxTurns', 'permissionMode', 'mcpServers', 'skills']
    .filter((k) => Array.isArray(fm[k]) ? fm[k].length > 0 : Boolean(fm[k]));
  const snap = { kind, name, source, cwd, cfg, body, description: fm.description, records, settings,
    sourceSha256: hash(raw), untranslated };
  if (Buffer.byteLength(bundle(snap)) > cfg.maxContextBytes) throw new Error(`${name}: complete instructions and knowledge exceed maxContextBytes (${cfg.maxContextBytes})`);
  return snap;
}

function receipt(snap, channel) {
  return { kind: snap.kind, name: snap.name, source: real(snap.source), sourceSha256: snap.sourceSha256, channel,
    files: snap.records.map((r) => ({ name: r.declared, path: r.realPath, bytes: r.bytes, lines: r.lines, sha256: r.sha256 })) };
}

function bundle(snap) {
  const parts = [`# kload: ${snap.kind} ${snap.name}`, '',
    `Shared source: ${real(snap.source)}`, `Source SHA-256: ${snap.sourceSha256}`, '',
    'The declared knowledge below is attached in full. Use these contents; do not reopen the originals just to load them.',
    'If any required section is absent, stop and report incomplete delivery. Never infer missing content.',
    `Start the result with: KNOWLEDGE: ${snap.records.map((r) => r.declared).join(' · ') || 'none declared'}`, '',
    '## Agent or skill instructions', '', snap.body, ''];
  for (const r of snap.records) parts.push(`## Knowledge: ${r.declared}`, '',
    `<!-- KLOAD BEGIN ${r.declared} sha256=${r.sha256} bytes=${r.bytes} -->`,
    r.content, `<!-- KLOAD END ${r.declared} sha256=${r.sha256} -->`, '');
  return parts.join('\n');
}

function skillView(snap) {
  return `---\nname: ${snap.name}\ndescription: ${JSON.stringify(snap.description)}\n---\n\n<!-- ${OWNER} -->\n\n${bundle(snap)}\n`;
}

function sources(cfg, kind) {
  const found = new Map();
  for (const dir of cfg[kind === 'agent' ? 'agentDirs' : 'skillDirs']) {
    if (!exists(dir)) continue;
    for (const item of fs.readdirSync(dir).sort()) {
      const source = kind === 'agent' || item.endsWith('.md') ? path.join(dir, item) : path.join(dir, item, 'SKILL.md');
      if (kind === 'agent' && !item.endsWith('.md')) continue;
      const name = item.replace(/\.md$/, '');
      if (!safeName(name) || found.has(name)) continue;
      // Keep broken source links visible, so a stale export is disabled.
      if (exists(source) || (kind === 'skill' && exists(path.join(dir, item)))) found.set(name, source);
    }
  }
  return found;
}

function ownedLink(link, target) {
  // Codex treats agent TOML as protected configuration. Write owned generated
  // TOML at the native path; only skill folders use discovery symlinks.
  if (path.resolve(link) === path.resolve(target)) {
    try { return fs.lstatSync(link).isFile() && fs.readFileSync(link, 'utf8').startsWith(`# ${OWNER};`); }
    catch { return false; }
  }
  try { return fs.lstatSync(link).isSymbolicLink() && path.resolve(path.dirname(link), fs.readlinkSync(link)) === path.resolve(target); }
  catch { return false; }
}

function pathsFor(scope, kind, name) {
  const link = path.join(kind === 'agent' ? scope.agents : scope.skills, kind === 'agent' ? `${name}.toml` : name);
  const target = kind === 'agent' ? link : path.join(scope.generated, 'skills', name);
  return { target, link, view: kind === 'agent' ? target : path.join(target, 'SKILL.md') };
}

function syncScope(scope) {
  fs.mkdirSync(scope.generated, { recursive: true });
  const lock = path.join(scope.generated, '.sync-lock');
  const deadline = Date.now() + 4000;
  while (true) {
    try { fs.mkdirSync(lock); fs.writeFileSync(path.join(lock, 'pid'), String(process.pid)); break; }
    catch (e) {
      if (e.code !== 'EEXIST') throw e;
      try { const pid = Number(fs.readFileSync(path.join(lock, 'pid'), 'utf8')); if (pid) process.kill(pid, 0); }
      catch (e) { if (e.code === 'ESRCH') { fs.rmSync(lock, { recursive: true }); continue; } }
      if (Date.now() >= deadline) throw new Error('Another kload refresh is still running');
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 25);
    }
  }
  try {
    const file = path.join(scope.generated, 'manifest.json');
    const previous = json(file, { entries: {} });
    const entries = {}, errors = [], updated = [];
    const cfg = config(scope.cwd);
    for (const kind of ['agent', 'skill']) for (const [name, source] of sources(cfg, kind)) {
      const key = `${kind}:${name}`;
      const dest = pathsFor(scope, kind, name);
      const entry = { kind, name, source, ...dest, cwd: scope.cwd };
      entries[key] = entry;
      try {
        if (exists(dest.link) && !ownedLink(dest.link, dest.target)) throw new Error(`Existing registration is owned elsewhere: ${dest.link}`);
        const snap = snapshot(kind, name, source, scope.cwd);
        let content;
        if (kind === 'agent') {
          // Runtime-specific settings only. The legacy model, tools and turn
          // limits are recorded, never copied as incompatible Codex settings.
          content = `# ${OWNER}; edit ${real(source)}\n`;
          for (const [k, v] of Object.entries({ name, description: snap.description, ...snap.settings,
            developer_instructions: `${OWNER}. Shared source: ${real(source)}\n\nKload supplies this agent's current instructions and declared knowledge at SubagentStart. Follow that complete kload bundle. If the bundle did not arrive, report the failure and do not perform the task.` })) {
            content += `${k} = ${JSON.stringify(v)}\n`;
          }
        } else {
          content = skillView(snap);
        }
        if (atomicWrite(dest.view, content)) updated.push(key);
        if (kind === 'skill') {
          const wanted = new Set();
          // Keep the wrapper's assets, not the directory of a symlinked SKILL.md.
          for (const asset of fs.readdirSync(path.dirname(source))) {
            if (asset === 'SKILL.md' || asset.startsWith('.')) continue;
            // Flat <name>.md skills have no dedicated asset directory.
            if (path.basename(source) !== 'SKILL.md') continue;
            const target = path.join(dest.target, asset), origin = path.join(path.dirname(source), asset);
            wanted.add(asset);
            if (exists(target) && fs.lstatSync(target).isSymbolicLink() && real(target) !== real(origin)) fs.unlinkSync(target);
            if (!exists(target)) fs.symlinkSync(path.resolve(origin), target);
          }
          for (const asset of fs.readdirSync(dest.target)) {
            const target = path.join(dest.target, asset);
            if (fs.lstatSync(target).isSymbolicLink() && !wanted.has(asset)) fs.unlinkSync(target);
          }
        }
        fs.mkdirSync(path.dirname(dest.link), { recursive: true });
        if (!exists(dest.link)) fs.symlinkSync(path.resolve(dest.target), dest.link);
        Object.assign(entry, receipt(snap, 'generated'), { settings: snap.settings, untranslated: snap.untranslated });
      } catch (e) {
        entry.error = e.message;
        errors.push(`${key}: ${e.message}`);
        if (ownedLink(dest.link, dest.target)) fs.unlinkSync(dest.link);
      }
    }
    for (const [key, old] of Object.entries(previous.entries)) if (!entries[key]) {
      if (!safeName(old.name) || !['agent', 'skill'].includes(old.kind)) continue;
      const dest = pathsFor(scope, old.kind, old.name);
      if (ownedLink(dest.link, dest.target)) fs.unlinkSync(dest.link);
      // Keep a tombstone so a cached agent type cannot run stale instructions.
      entries[key] = { ...old, ...dest, error: 'Source definition was removed' };
    }
    atomicWrite(file, JSON.stringify({ version: 1, entries }, null, 2) + '\n');
    return { scope: scope.root || 'user', updated, errors, entries };
  } finally { fs.rmSync(lock, { recursive: true, force: true }); }
}

function synchronize(cwd) { return scopes(cwd).map(syncScope); }

function capabilities(cwd) {
  const selected = new Map();
  for (const scope of scopes(cwd).reverse()) {
    const manifest = json(path.join(scope.generated, 'manifest.json'), { entries: {} });
    for (const [key, entry] of Object.entries(manifest.entries)) {
      if (selected.has(key)) continue;
      if (!safeName(entry.name) || !['agent', 'skill'].includes(entry.kind)) continue;
      const dest = pathsFor(scope, entry.kind, entry.name);
      if (exists(dest.link) && !ownedLink(dest.link, dest.target)) { selected.set(key, null); continue; }
      selected.set(key, { ...entry, ...dest });
    }
  }
  return selected;
}

function logReceipt(input, snap, channel) {
  const file = path.join(CODEX, 'kload', 'receipts.jsonl');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.appendFileSync(file, JSON.stringify({ time: new Date().toISOString(), session: input.session_id,
    turn: input.turn_id, agent: input.agent_id, ...receipt(snap, channel) }) + '\n', { mode: 0o600 });
}

function loadEntry(entry, cwd) {
  // Resolve on every invocation; the receipt and injected bytes use one read.
  if (!entry) return null;
  if (entry.error && !exists(entry.source)) throw new Error(`${entry.name}: ${entry.error}`);
  return snapshot(entry.kind, entry.name, entry.source, cwd);
}

function deny(event, message) {
  const reason = `kload: ${message}`;
  if (event === 'UserPromptSubmit') return { decision: 'block', reason };
  if (event === 'PreToolUse') return { hookSpecificOutput: { hookEventName: event, permissionDecision: 'deny', permissionDecisionReason: reason } };
  // SubagentStart cannot cancel a child. PreToolUse is the normal launch gate.
  return { systemMessage: reason, hookSpecificOutput: { hookEventName: event,
    additionalContext: `KLOAD DELIVERY FAILED. Do not perform the task. Report this error: ${reason}` } };
}

function contextOutput(input, snaps, channel) {
  if (!snaps.length) return null;
  const text = snaps.map(bundle).join('\n\n');
  const limit = Math.min(...snaps.map((s) => s.cfg.maxContextBytes));
  if (Buffer.byteLength(text) > limit) throw new Error(`Combined knowledge payload exceeds maxContextBytes (${limit})`);
  for (const snap of snaps) logReceipt(input, snap, channel);
  return { systemMessage: snaps.map((s) => `kload: ${s.kind} ${s.name}: ${s.records.length}/${s.records.length} knowledge files attached`).join('\n'),
    hookSpecificOutput: { hookEventName: input.hook_event_name, additionalContext: text } };
}

function strings(value) {
  if (typeof value === 'string') return [value];
  if (Array.isArray(value)) return value.flatMap(strings);
  if (value && typeof value === 'object') return Object.values(value).flatMap(strings);
  return [];
}

function handle(input) {
  const cwd = path.resolve(input.cwd || process.cwd()), event = input.hook_event_name;
  if (!['SessionStart', 'UserPromptSubmit', 'PreToolUse', 'SubagentStart'].includes(event)) return null;
  try {
    if (event === 'SessionStart' || event === 'UserPromptSubmit') {
      const results = synchronize(cwd);
      const errors = results.flatMap((r) => r.errors);
      if (event === 'SessionStart') return errors.length ? { systemMessage: `kload refresh: ${errors.join('; ')}` } : null;
    }
    const entries = capabilities(cwd);
    if (event === 'UserPromptSubmit') {
      const names = [...new Set([...String(input.prompt || '').matchAll(/(?:^|[\s(])\$([a-zA-Z0-9][a-zA-Z0-9_-]*)(?![\w:-])/g)].map((m) => m[1]))];
      return contextOutput(input, names.map((n) => loadEntry(entries.get(`skill:${n}`), cwd)).filter(Boolean), 'explicit-skill');
    }
    if (event === 'SubagentStart') {
      const snap = loadEntry(entries.get(`agent:${input.agent_type}`), cwd);
      return contextOutput(input, snap ? [snap] : [], 'subagent-start');
    }
    const ti = input.tool_input || {};
    if (['spawn_agent', 'Agent', 'Task'].includes(input.tool_name)) {
      const name = ti.agent_type || ti.subagent_type;
      const snap = loadEntry(entries.get(`agent:${name}`), cwd);
      // Native agent files carry runtime settings; this preflight gates missing
      // dependencies before SubagentStart, where Codex cannot stop the child.
      return snap ? { systemMessage: `kload: ${name} prerequisites verified; knowledge will be attached to the child` } : null;
    }
    // Codex has no universal Skill tool event. Implicit activation reads a
    // registered SKILL.md; attach complete instructions before that read, even
    // when the model asks the read tool for a truncated excerpt.
    const args = strings(ti).join('\n');
    const snaps = [];
    for (const entry of entries.values()) {
      if (!entry || entry.kind !== 'skill') continue;
      const paths = [entry.view, path.join(entry.link, 'SKILL.md'), entry.source];
      if (paths.some((p) => args.includes(p) || args.includes(p.replace(HOME, '~')))) {
        const snap = loadEntry(entry, cwd);
        // The impending read must not return an older fallback bundle that
        // contradicts the freshly injected instructions or knowledge.
        if (ownedLink(entry.link, entry.target)) atomicWrite(entry.view, skillView(snap));
        snaps.push(snap);
      }
    }
    return contextOutput(input, snaps.filter(Boolean), 'implicit-skill-read');
  } catch (e) { return deny(event, e.message); }
}

function main() {
  if (process.argv[2] === 'sync') {
    const results = synchronize(path.resolve(process.argv[3] || process.cwd()));
    console.log(JSON.stringify(results.map(({ entries, ...r }) => ({ ...r,
      agents: Object.values(entries).filter((e) => e.kind === 'agent' && !e.error).length,
      skills: Object.values(entries).filter((e) => e.kind === 'skill' && !e.error).length })), null, 2));
    return results.some((r) => r.errors.length) ? 1 : 0;
  }
  const raw = fs.readFileSync(0, 'utf8');
  if (!raw.trim()) return 0;
  const out = handle(JSON.parse(raw));
  if (out) console.log(JSON.stringify(out));
  return 0;
}

if (require.main === module) {
  try { process.exitCode = main(); }
  catch (e) { console.error(`kload Codex: ${e.message}`); process.exitCode = 1; }
} else module.exports = { config, runtimeSettings, snapshot, bundle, receipt, scopes, synchronize, capabilities, handle, MAX_CONTEXT };
