'use strict';

/**
 * Native OpenCode adapter. Authored definitions remain in their original
 * folders; OpenCode never holds a copy of an agent.
 *
 *   config               registers every shared agent as a native subagent
 *   tool.execute.before  task: prepends the declared knowledge to the child's prompt
 *                        skill: preflight, so a missing file blocks the load
 *   tool.execute.after   skill: replaces the loaded body with the current source
 *                        and its complete knowledge
 *
 * OpenCode reads .claude/skills natively but never .claude/agents, and a Claude
 * agent file symlinked into its agents folder parses wrong (model becomes a
 * provider id, mode becomes "all", unknown keys reach the provider as options).
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const K = require('./kload.js');

const HOME = os.homedir();
const OPENCODE = process.env.KLOAD_OPENCODE_DIR
  || path.join(process.env.XDG_CONFIG_HOME || path.join(HOME, '.config'), 'opencode');
const DATA = process.env.KLOAD_OPENCODE_DATA
  || path.join(process.env.XDG_DATA_HOME || path.join(HOME, '.local', 'share'), 'opencode');
const MAX_CONTEXT = 192 * 1024;
const CODEX_VIEW = 'Generated by kload for Codex';
// Built-in and hidden OpenCode agents. A shared definition never replaces one.
const RESERVED = new Set(['build', 'plan', 'general', 'explore', 'compaction', 'title', 'summary']);
const CHANGED = 'Your definition was edited after this session started. These instructions are current and supersede your system prompt.';

// Claude built-in tool -> the OpenCode permission keys it corresponds to.
const CLAUDE_TOOLS = {
  Read: ['read'], Write: ['edit'], Edit: ['edit'], MultiEdit: ['edit'], NotebookEdit: ['edit'],
  Bash: ['bash'], Grep: ['grep'], Glob: ['glob', 'list'], LS: ['list'], LSP: ['lsp'],
  WebFetch: ['webfetch'], WebSearch: ['websearch'], Task: ['task'], Agent: ['task'],
  TodoWrite: ['todowrite'], Skill: ['skill'], AskUserQuestion: ['question'],
};
const OPENCODE_TOOLS = ['read', 'edit', 'glob', 'grep', 'list', 'bash', 'task', 'todowrite',
  'webfetch', 'websearch', 'skill', 'lsp', 'question'];
const SETTINGS = { model: 'string', variant: 'string', temperature: 'number', top_p: 'number', steps: 'integer' };

const hash = (s) => crypto.createHash('sha256').update(s).digest('hex');
const exists = (p) => { try { fs.lstatSync(p); return true; } catch { return false; } };
const real = (p) => { try { return fs.realpathSync(p); } catch { return path.resolve(p); } };
const json = (p) => exists(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : {};
const safeName = (s) => typeof s === 'string' && /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(s);

/** A failure kload must surface by stopping the call, not swallow. */
class Blocked extends Error {}

function config(cwd) {
  // kload's roots, discovery and precedence; OpenCode-specific settings last.
  const cfg = K.loadConfig(cwd);
  for (const f of [path.join(OPENCODE, 'kload.json'), path.join(cwd, '.opencode', 'kload.json')]) {
    Object.assign(cfg, json(f));
  }
  for (const [key, leaf] of [['agentDirs', 'agents'], ['skillDirs', 'skills'], ['knowledgeDirs', 'knowledge']]) {
    if (!Array.isArray(cfg[key]) || cfg[key].some((p) => typeof p !== 'string')) throw new Error(`${key} must be an array of paths`);
    cfg[key] = K.effectiveDirs(cfg[key].map((p) => p.replaceAll('{opencode}', OPENCODE)), cwd, cfg, leaf);
  }
  cfg.maxContextBytes = cfg.maxContextBytes || MAX_CONTEXT;
  if (!Number.isSafeInteger(cfg.maxContextBytes) || cfg.maxContextBytes < 1024 || cfg.maxContextBytes > 1024 * 1024) {
    throw new Error('maxContextBytes must be between 1024 and 1048576');
  }
  cfg.maxFileBytes = cfg.maxContextBytes;
  cfg.strictUtf8 = true;
  return cfg;
}

/** The `runtimes: opencode:` block of a shared definition. */
function runtimeBlock(frontmatter, fm) {
  if (typeof fm.runtimes === 'string' && fm.runtimes.trim().startsWith('{')) return JSON.parse(fm.runtimes).opencode || {};
  const lines = frontmatter.split('\n');
  const start = lines.findIndex((l) => /^runtimes:\s*(?:#.*)?$/.test(l));
  if (start < 0) return {};
  let child = -1, indentation = 0;
  const body = [];
  for (let i = start + 1; i < lines.length; i++) {
    const l = lines[i];
    if (l.trim() && !/^\s/.test(l)) break;
    if (child < 0) {
      const m = /^(\s+)opencode:\s*(?:#.*)?$/.exec(l);
      if (m) { child = i; indentation = m[1].length; }
      continue;
    }
    if (l.trim() && l.match(/^\s*/)[0].length <= indentation) break;
    body.push(l.slice(indentation + 2));
  }
  return K.parseYamlSubset(body.join('\n'));
}

/**
 * Only documented OpenCode agent settings. The Claude model is never copied:
 * it is not a provider/model id, and the subagent inherits the caller's model.
 * max_turns carries over as steps. Precedence: defaults < overrides < frontmatter.
 */
function runtimeSettings(frontmatter, fm, cfg, name) {
  const turns = fm.max_turns || fm.maxTurns;
  const merged = Object.assign({}, turns ? { steps: turns } : {}, cfg.agentDefaults || {},
    (cfg.agentOverrides || {})[name] || {}, runtimeBlock(frontmatter, fm));
  const out = {};
  for (const [k, v] of Object.entries(merged)) {
    if (k === 'permission') {
      if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('OpenCode permission override must be an object');
      out.permission = v;
      continue;
    }
    const type = SETTINGS[k];
    if (!type) throw new Error(`Unsupported OpenCode runtime setting: ${k}`);
    const value = typeof v === 'string' ? v.replace(/\s+#.*$/, '').trim() : v;
    if (value === 'inherit') continue;
    if (type === 'string') {
      if (typeof value !== 'string' || !value) throw new Error(`Invalid OpenCode ${k}`);
      out[k] = value;
    } else {
      const n = Number(value);
      if (value === '' || !Number.isFinite(n) || (type === 'integer' && (!Number.isInteger(n) || n < 1))) throw new Error(`Invalid OpenCode ${k}`);
      out[k] = n;
    }
  }
  if (out.model && !/^[^\s/]+\/\S+$/.test(out.model)) throw new Error(`OpenCode model must be provider/model, got ${out.model}`);
  return out;
}

function toolNames(v) {
  const list = Array.isArray(v) ? v : typeof v === 'string' ? v.split(',') : [];
  return list.map((t) => String(t).replace(/\(.*$/, '').trim()).filter(Boolean);
}

/**
 * A whitelist of Claude built-ins becomes deny rules for every OpenCode tool it
 * does not grant. A list naming anything else was written for another runner
 * (Zora or MCP tool names); it is recorded as untranslated, never guessed at.
 */
function translateTools(fm) {
  const allowed = toolNames(fm.tools), denied = toolNames(fm.disallowedTools);
  const permission = {}, untranslated = [];
  if (allowed.length && !allowed.includes('*')) {
    if (allowed.every((t) => CLAUDE_TOOLS[t])) {
      const granted = new Set(allowed.flatMap((t) => CLAUDE_TOOLS[t]));
      for (const key of OPENCODE_TOOLS) if (!granted.has(key)) permission[key] = 'deny';
    } else {
      untranslated.push('tools');
    }
  }
  for (const t of denied) for (const key of CLAUDE_TOOLS[t] || []) permission[key] = 'deny';
  if (denied.some((t) => !CLAUDE_TOOLS[t])) untranslated.push('disallowedTools');
  for (const k of ['permissionMode', 'mcpServers', 'skills']) {
    if (Array.isArray(fm[k]) ? fm[k].length : fm[k]) untranslated.push(k);
  }
  return { permission, untranslated };
}

function parse(kind, name, source) {
  const raw = fs.readFileSync(source, 'utf8');
  const [frontmatter, body] = K.splitFrontmatter(raw);
  if (!frontmatter) throw new Error(`${name}: missing frontmatter`);
  const fm = K.parseYamlSubset(frontmatter);
  if (!safeName(name) || fm.name !== name) throw new Error(`${name}: name must match the source filename/directory`);
  if (!fm.description || typeof fm.description !== 'string') throw new Error(`${name}: missing description`);
  // A malformed config with knowledge must never look like an empty declaration.
  if (fm.config && typeof fm.config === 'string') JSON.parse(fm.config);
  return { kind, name, source, frontmatter, fm, body, description: fm.description,
    files: [...new Set(K.declaredKnowledge(fm).files)], sourceSha256: hash(raw) };
}

/** Does this source declare knowledge? Unparseable config counts as yes. */
function declares(source) {
  try {
    const [frontmatter] = K.splitFrontmatter(fs.readFileSync(source, 'utf8'));
    const fm = K.parseYamlSubset(frontmatter || '');
    if (K.declaredKnowledge(fm).files.length) return true;
    if (typeof fm.config === 'string' && fm.config.trim()) JSON.parse(fm.config);
    return false;
  } catch { return true; }
}

/** Resolve on every invocation; the report, receipt and payload use one read. */
function snapshot(kind, name, source, cwd) {
  const cfg = config(cwd);
  const def = parse(kind, name, source);
  const records = def.files.map((file) => {
    const rec = K.resolveKnowledgeFile(file, cwd, cfg);
    return { ...rec, sha256: rec.status === 'ok' ? hash(rec.content) : null };
  });
  const failures = records.filter((r) => r.status !== 'ok');
  if (failures.length) throw new Error(`${name}: ${failures.map((r) => `${r.declared}: ${r.detail}`).join('; ')}`);
  const snap = { ...def, cfg, records };
  if (Buffer.byteLength(bundle(snap, def.body)) > cfg.maxContextBytes) {
    throw new Error(`${name}: complete instructions and knowledge exceed maxContextBytes (${cfg.maxContextBytes})`);
  }
  return snap;
}

function bundle(snap, instructions) {
  const parts = [`# kload: ${snap.kind} ${snap.name}`, '',
    `Shared source: ${real(snap.source)}`, `Source SHA-256: ${snap.sourceSha256}`, '',
    'The declared knowledge below is attached in full. Use these contents; do not reopen the originals just to load them.',
    'If any required section is absent, stop and report incomplete delivery. Never infer missing content.',
    `Start the result with: KNOWLEDGE: ${snap.records.map((r) => r.declared).join(' · ') || 'none declared'}`, ''];
  if (instructions) parts.push(`## ${snap.kind === 'agent' ? 'Agent' : 'Skill'} instructions`, '', instructions.trim(), '');
  for (const r of snap.records) parts.push(`## Knowledge: ${r.declared}`, '',
    `<!-- KLOAD BEGIN ${r.declared} sha256=${r.sha256} bytes=${r.bytes} -->`,
    r.content, `<!-- KLOAD END ${r.declared} sha256=${r.sha256} -->`, '');
  return parts.join('\n');
}

function agentSources(cfg) {
  const found = new Map();
  for (const dir of cfg.agentDirs) {
    let items;
    try { items = fs.readdirSync(dir).sort(); } catch { continue; }
    for (const item of items) {
      const name = item.replace(/\.md$/, '');
      if (!item.endsWith('.md') || !safeName(name) || found.has(name)) continue;
      // lstat, so a broken link surfaces as a registration error, not silence.
      if (exists(path.join(dir, item))) found.set(name, path.join(dir, item));
    }
  }
  return found;
}

/** Add every shared agent to OpenCode's live config as a native subagent. */
function register(oc, cwd, registered) {
  const cfg = config(cwd);
  const agents = oc.agent || (oc.agent = {});
  const report = { registered: [], skipped: [], errors: [] };
  for (const [name, source] of agentSources(cfg)) {
    if (RESERVED.has(name) || agents[name]) {
      report.skipped.push(`${name}: already defined in OpenCode`);
      continue;
    }
    try {
      const def = parse('agent', name, source);
      const { permission, untranslated } = translateTools(def.fm);
      const { permission: override, ...settings } = runtimeSettings(def.frontmatter, def.fm, cfg, name);
      const rules = { ...permission, ...(override || {}) };
      agents[name] = { description: def.description, mode: 'subagent', prompt: def.body.trim(), ...settings,
        ...(Object.keys(rules).length ? { permission: rules } : {}) };
      registered.set(name, { source, sourceSha256: def.sourceSha256, untranslated });
      report.registered.push(name);
    } catch (e) {
      report.errors.push(`${name}: ${e.message}`);
    }
  }
  return report;
}

/** Swap the skill body OpenCode loaded for the current source and its knowledge. */
function replaceSkillBody(output, name, content) {
  const head = `<skill_content name="${name}">\n# Skill: ${name}\n\n`;
  const tail = output.lastIndexOf('\n\nBase directory for this skill: ');
  if (output.startsWith(head) && tail >= head.length) return head + content + output.slice(tail);
  // Unrecognized layout: deliver after it rather than drop anything.
  return `${output}\n\n${content}`;
}

function report(snap) {
  const rows = snap.records.map((r) => `✓ ${r.declared} · ${r.lines} lines`);
  const stale = snap.cfg.warnStale && K.detectStaleSelfLoad(snap.body, snap.files);
  if (stale) rows.push(`⚠ stale self-load block: ${stale.join('; ')}`);
  rows.push(`${snap.records.length}/${snap.records.length} loaded`);
  return { title: `kload · ${snap.name} ${snap.kind}`, message: rows.join('\n'), variant: stale ? 'warning' : 'success' };
}

function logReceipt(input, snap, channel) {
  const file = path.join(DATA, 'kload', 'receipts.jsonl');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.appendFileSync(file, JSON.stringify({ time: new Date().toISOString(), session: input.sessionID,
    call: input.callID, kind: snap.kind, name: snap.name, source: real(snap.source), sourceSha256: snap.sourceSha256,
    channel, files: snap.records.map((r) => ({ name: r.declared, path: r.realPath, bytes: r.bytes, lines: r.lines, sha256: r.sha256 })) }) + '\n',
  { mode: 0o600 });
}

function plugin({ client, directory } = {}) {
  const cwd = path.resolve(directory || process.cwd());
  const registered = new Map();
  let pending = null;

  // Display is best effort: no TUI (opencode run) or a failed call never matters.
  const toast = (body) => {
    try { Promise.resolve(client?.tui?.showToast({ body: { duration: 8000, ...body } })).catch(() => {}); } catch {}
  };
  const log = (level, message) => {
    try { Promise.resolve(client?.app?.log({ body: { service: 'kload', level, message } })).catch(() => {}); } catch {}
  };
  const blocked = (message) => {
    toast({ title: 'kload · delivery failed', message, variant: 'error', duration: 15000 });
    return new Blocked(`kload: ${message}`);
  };

  function beforeTask(input, args) {
    const entry = registered.get(args.subagent_type);
    // A resumed child already holds the knowledge it was started with.
    if (!entry || args.task_id) return;
    let snap;
    try { snap = snapshot('agent', args.subagent_type, entry.source, cwd); }
    catch (e) { throw blocked(e.message); }
    const changed = snap.sourceSha256 !== entry.sourceSha256;
    if (!snap.records.length && !changed) return;
    args.prompt = `${bundle(snap, changed ? `${CHANGED}\n\n${snap.body}` : null)}\n## Task\n\n${args.prompt || ''}`;
    if (snap.records.length) {
      args.description = `${args.description || snap.name} · kload ${snap.records.length}/${snap.records.length}`;
    }
    logReceipt(input, snap, 'task');
    toast(report(snap));
  }

  function skillSource(args) {
    return args && typeof args.name === 'string' ? K.findSkillFile(args.name, cwd, config(cwd)) : null;
  }

  function beforeSkill(args) {
    const source = skillSource(args);
    if (!source || !declares(source)) return;
    try { snapshot('skill', args.name, source, cwd); }
    catch (e) { throw blocked(e.message); }
  }

  function afterSkill(input, output) {
    const source = skillSource(input.args);
    if (!source || typeof output.output !== 'string') return;
    const name = input.args.name;
    let snap;
    try { snap = snapshot('skill', name, source, cwd); }
    catch (e) {
      // The preflight passed, so a file changed in between. Say so in-context.
      if (declares(source)) {
        output.output = `KLOAD DELIVERY FAILED. Do not perform the task. Report this error: kload: ${e.message}`;
        blocked(e.message);
      }
      return;
    }
    // Codex's generated views in ~/.agents/skills shadow ~/.claude/skills in
    // OpenCode's discovery and are only as fresh as Codex's last refresh.
    const codexView = output.output.includes(CODEX_VIEW);
    if (!snap.records.length && !codexView) return;
    const content = snap.records.length ? bundle(snap, snap.body) : snap.body.trim();
    output.output = replaceSkillBody(output.output, name, content);
    if (!snap.records.length) return;
    output.title = `${output.title || `Loaded skill: ${name}`} · kload ${snap.records.length}/${snap.records.length}`;
    logReceipt(input, snap, 'skill');
    toast(report(snap));
  }

  return {
    config: async (oc) => {
      try {
        const result = register(oc, cwd, registered);
        log('info', `registered ${result.registered.length} shared agents`);
        const problems = [...result.errors, ...result.skipped];
        if (problems.length) {
          log('warn', problems.join('\n'));
          if (result.errors.length) pending = result.errors;
        }
      } catch (e) {
        log('error', `agent registration failed: ${e.message}`);
        pending = [e.message];
      }
    },
    // Registration runs before the TUI is listening; report problems once it is.
    event: async ({ event }) => {
      if (!pending || !event || event.type !== 'session.created') return;
      toast({ title: 'kload · agents not registered', message: pending.join('\n'), variant: 'warning', duration: 15000 });
      pending = null;
    },
    'tool.execute.before': async (input, output) => {
      try {
        if (input.tool === 'task' && output.args) beforeTask(input, output.args);
        else if (input.tool === 'skill') beforeSkill(output.args);
      } catch (e) {
        if (e instanceof Blocked) throw e;
        log('error', `${input.tool}: ${e.stack || e.message}`);
      }
    },
    'tool.execute.after': async (input, output) => {
      try {
        if (input.tool === 'skill') afterSkill(input, output);
      } catch (e) {
        log('error', `${input.tool}: ${e.stack || e.message}`);
      }
    },
  };
}

module.exports = { plugin, config, register, runtimeSettings, translateTools, snapshot, bundle, replaceSkillBody, report, MAX_CONTEXT };
